### ISSUE TITLE
Запуск теста в windows через консоль gradlew test

### ISSUE THREAD

**Issue by sheriff777** [sheriff777/hw4#2]
Предусловие:
Открыта страница http://localhost:9999/

Шаги воспроизведения:
- Запуск теста через ПУСК;
- Запуск теста в windows через консоль  gradlew test.

Ожидаемый результат:
В обоих случаях должно сработать.

Фактический результат:
В 1 случае все отлично, во 2 случае ошибка.

Окружение:
ОС: Windows 10 Корпоративная 2016,
Версия ОС: 1607,
Построение ОС: 14393.3443
Версия Java: 1.8.0.242

Последняя версия Google Chrome уже установлена
Версия 79.0.3945.130 (Официальная сборка), (64 бит)

.

![Screenshot_1](https://user-images.githubusercontent.com/56364272/74052966-17095180-4a05-11ea-87d2-8231a349d930.jpg)

**Comment by coursar** [comment]
У вас jar'ник wrapper'а пустой: https://raw.githubusercontent.com/sheriff777/hw4/master/gradle/wrapper/gradle-wrapper.jar (0 байт)

А должен быть непустой
